CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    login    VARCHAR(20) UNIQUE,
    name     VARCHAR(30),
    email    VARCHAR(50) UNIQUE,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS mpa
(
    id   INTEGER     NOT NULL PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER     NOT NULL PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    name         VARCHAR(40) NOT NULL,
    description  TEXT(1000),
    release_date DATE,
    duration     INTEGER,
    mpa_id       INTEGER,
    FOREIGN KEY (mpa_id) REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    film_id  INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    FOREIGN KEY (film_id) REFERENCES films (id),
    FOREIGN KEY (genre_id) REFERENCES genres (id),
    CONSTRAINT unique_film_genre_pair UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    user1_id  BIGINT  NOT NULL,
    user2_id  BIGINT  NOT NULL,
    CONSTRAINT unique_users_pair UNIQUE (user1_id, user2_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (film_id) REFERENCES films (id)
);
